spring.application.name=payments

# Import .env file
spring.config.import=optional:file:./.env[.properties]

# toss API Key
widgetSecretKey=${WIDGET_SECRET_KEY}

# Mysql
spring.datasource.url=jdbc:mysql:${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=${DB_DRIVER:com.mysql.cj.jdbc.Driver}

# JPA
spring.jpa.hibernate.ddl-auto=create